name: Update Medium Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'        # daily
  workflow_dispatch:

permissions:
  contents: write              # built‑in GITHUB_TOKEN to push

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@Shakeelkhuhro"

      - name: Commit & push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          git add README.md
          git commit -m "🔄 chore: update README with latest Medium posts" || exit 0
          git push origin HEAD:main
